repos:
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.77.1
      hooks:
        - id: terraform_fmt
          always_run: true
    - repo: local
      hooks:
        - id: terraform-readme
          name: terraform-readme
          entry: tools/terraform-doc.sh
          language: script
          types: [terraform]
          exclude: (\.terraform|test\/.*$|examples\/.*$)
          pass_filenames: true
          require_serial: true
          always_run: true
          verbose: true