kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cluster-filestore
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: $NFS_TIER
  network: $PREFIX
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cluster-filestore
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: cluster-filestore
  resources:
    requests:
      storage: $NFS_SIZE
