cluster:
  nNodes: 8
  nodePool: np-1
network:
  useTcpx: "yes"
  ncclIfnames: 'eth0'
  ncclPlugin: us-docker.pkg.dev/gce-ai-infra/gpudirect-tcpx/nccl-plugin-gpudirecttcpx-dev:v3.1.6_2023_10_06
  rxdmContainer: us-docker.pkg.dev/gce-ai-infra/gpudirect-tcpx/tcpgpudmarxd-dev:v2.0.9
  disablePmtu: "yes"
workload:
  jobTimestamp: # Must be defined
  gcsExperimentBucket: # Must be defined
  experimentDir: llama2-70b
  gcsDataBucket: litgpt-public-bucket
  dataDir: openwebtext_dataset
  image: us-docker.pkg.dev/gce-ai-infra/litgpt-full/litgpt
  modelName: Llama-2-70b-hf
  batchSize: 6
  microBatchSize: 6
  warmupIters: 10
  maxIters: 1000
  