cluster:
  nNodes: 8
  nodePool: np-1
network:
  useTcpx: 'yes'
  ncclIfnames: 'eth0'
  ncclPlugin: us-docker.pkg.dev/gce-ai-infra/gpudirect-tcpx/nccl-plugin-gpudirecttcpx-dev:v3.1.6_2023_10_06
  rxdmContainer: us-docker.pkg.dev/gce-ai-infra/gpudirect-tcpx/tcpgpudmarxd-dev:v2.0.9
  disablePmtu: 'yes'

workload:
  image: us-central1-docker.pkg.dev/supercomputer-testing/pirillo-gcr/llm-foundry-flash-attn2:37
  modelName: mpt-70b
  gcsBucket: pirillo-sct-bucket
  collectNsysProfile: "no" # Currently does not work
  collectComposerProfile: "no" # set to "yes" to enable
  jobTimestamp: 1
  experimentDir: '/'
  dataDir: '/'
  maxSeqLen: 4096
  numBatches: 30
  globalBatchSize: 128
  dtms: 2
  ncclNsocksPerthread: 4
  ncclSocketNThreads: 1
  ncclMaxChannels: 12
  ncclMinChannels: 12
  actCkpt: true