# Run metadata.
runUser: "unknown"
versionVec: "unknown"
description: "unknown"
# Do NOT set this field unless you are certain you are using LKG configs.
# This will tamper with performance regression detection in future runs.
isLkg: false

cluster:
  nNodes: null  # Must specify on commandline (--set cluster.nNodes=2)
  # Must only specify one of topology aware and node-pool placement.
  topologyAware: false
  npPlacement: false
  nNps: 1
  startNp: 1
  gcsBucket: "nccl-benchmarks-fastrak"

ncclBenchmarks:
  image: "us-docker.pkg.dev/kernel-net-team/gpudirect-tcpx/nccl-benchmarks"
  tag: "latest"
  # A comma-separated list of benchmarks to run.
  benchmarks: "AllGather"
  # A comma-separated list of hex masks for the benchmarks.
  # Must be of the same length as ncclBenchmarks.benchmarks.
  # Each mask must be less than ncclBenchmarks.gpusPerNode.
  masks: "0x0"
  # A comma-separated list of message sizes, used by all benchmarks.
  msgSizes: "1M,2M,4M,8M,16M,32M,64M,128M,256M,512M,1G,2G,4G,8G"
  # Number of GPUs per node. Must be one of 1, 2, 4, 8.
  gpusPerNode: 8
  nComms: 1
  warmupIters: 5
  runIters: 100
  nRuns: 5
  dataCheck: false

# Modularized telemetry.
# Input is case insensitive. Default value is `none`.
# To enable all telemetry, set this field to `all`.
# To enable specific modules, set this field to a comma-separated list of
# desired components, e.g. `tcp,gpu`. Available modules are: nic, tcp, cpu,
# gpu, kernel.
telemetry: "none"

rxdm:
  image: null
  tag: null
  flags: null

ncclPlugin:
  image: null
  tag: null

unreservedCores: null

envs: null
