apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: pytorch
  # labels:
  #   kueue.x-k8s.io/queue-name: a3-queue    
spec:
  replicatedJobs:
    - name: workers
      template:
        spec:
          parallelism: 2
          completions: 2
          backoffLimit: 0
          template:
           spec:
            restartPolicy: Never
            containers:
            - name: pytorch
              image: gcr.io/k8s-staging-jobset/pytorch-resnet:latest
              ports:
              - containerPort: 3389
              env:
              - name: MASTER_ADDR
                value: "pytorch-workers-0-0.pytorch.default.svc.cluster.local"
              - name: MASTER_PORT
                value: "3389"
              command:
              - bash
              - -xc
              - |
                echo "Hello from $(hostname --fqdn)"
                torchrun --nproc_per_node=1 --nnodes=2 --rdzv_id=1001 --rdzv_backend=c10d --rdzv_endpoint=$MASTER_ADDR resnet.py --backend=gloo
              resources:
                limits:
                  nvidia.com/gpu: 8
