apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: a3-queue
spec:
  parallelism: 2
  completions: 4
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: nvidia/cuda:12.3.1-runtime-ubuntu20.04
        command: ["/bin/sh","-c"]
        args: ["nvidia-smi"]
        resources:
          limits:
            nvidia.com/gpu: 8
      restartPolicy: Never

